# Note autoscaling does not work with docker-desktop k8s as the metrics-server doesn't get any real usage data
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50