apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
---
apiVersion: v1
kind: ServiceAccount

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1